openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0
  description: Sample Orders API created by AI-assisted flow
servers:
  - url: https://api.example.com/v1
paths:
  /orders:
    get:
      summary: List orders
      operationId: listOrders
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderList'
    post:
      summary: Create an order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewOrder'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id: { type: string }
        item: { type: string }
        qty: { type: integer }
        price: { type: number }
    OrderList:
      type: object
      properties:
        total: { type: integer }
        items:
          type: array
          items:
            $ref: '#/components/schemas/Order'
    NewOrder:
      type: object
      properties:
        item: { type: string }
        qty: { type: integer }
security:
  - apiKeyAuth: []
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
